# Copyright 2026 BreezeDelegate
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/rust/rust_static_library.gni")

rust_static_library("rust") {
  allow_unsafe = true  # Required by the cxx FFI support.
  crate_root = "breeze_adblock_ffi.rs"
  sources = [ "breeze_adblock_ffi.rs" ]
  cxx_bindings = [ "breeze_adblock_ffi.rs" ]
  deps = [ "//third_party/rust/adblock/v0_13:lib" ]
}

source_set("breeze_adblock") {
  sources = [
    "breeze_adblock_cosmetic_observer.cc",
    "breeze_adblock_cosmetic_observer.h",
    "breeze_adblock_prefs.cc",
    "breeze_adblock_prefs.h",
    "breeze_adblock_service.cc",
    "breeze_adblock_service.h",
    "breeze_adblock_throttle.cc",
    "breeze_adblock_throttle.h",
  ]
  deps = [
    ":rust",
    "//base",
    "//chrome/browser/profiles:profile",
    "//chrome/common",
    "//components/pref_registry",
    "//components/prefs",
    "//content/public/browser",
    "//content/public/common",
    "//net",
    "//services/network/public/cpp",
    "//third_party/blink/public/common",
    "//ui/base",
    "//url",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "breeze_adblock_prefs_unittest.cc" ]
  deps = [
    ":breeze_adblock",
    "//components/sync_preferences:test_support",
    "//testing/gtest",
    "//url",
  ]
}
